### ISSUE TITLE
Test resource folder problem

### ISSUE THREAD

**Issue by albertotn** [quick-perf/maven-test-bench#12]
Only today I realize that #11 introduce a small problem: test resource folder is under a "b" subfolder:

> b/src/test/resources

not a big deal, but is better If I fix this too.

Long explanation: yesterday I made on my fork basic log4j setup but on master branch. I wanted to decouple log part from #10 , so I create a log branch. So I go back to my fork's master, create a patch, and then apply it to my local log branch. During patch apply there was this small mistake.

**Comment by jeanbisutti** [comment]
No problem Alberto. I did not notice this when I looked at the code. Thanks for your work.
