### ISSUE TITLE
Report execution time in maven-memory-allocation-{date-time}.csv file. 

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/maven-test-bench#3]
When `MvnValidateAllocationByMaven3VersionTest` is executed, results are exported into a `maven-memory-allocation-{date-time}.csv` file. You can consult an example [here](https://github.com/quick-perf/maven-test-bench/blob/master/measures/maven-memory-allocation-2019-09-01-18-48-41.csv).
For each Maven version and each measure of allocation, we want to report the length (seconds) in this file. You can add columns `Length 1 (s)`, `Length 2 (s)`, ... on the right. In addition, we would like to report the average length together with the minimum and the maximum length (it is already done for allocations).

**Implementation**

In `MvnValidateAllocationByMaven3VersionTest` class,  two lines of code are added in comment below to compute the length of an allocation measure:

```java
 private Long measureAllocation(Class<?> testClass) throws IOException {
        deleteQuickPerfFoldersInTemp();

        //long startTime = System.currentTimeMillis();
        PrintableResult printableResult = testResult(testClass);
        //long executionTimeInMilliseconds = System.currentTimeMillis() - startTime;
```

The CSV generation is done in `AllocationCsvExporter` class.

**Comment by albertotn** [comment]
Hi! I want to work on this, okay ?

**Comment by jeanbisutti** [comment]
Great! I assign the issue to you. Don't hesitate if I can help.

**Comment by jeanbisutti** [comment]
@albertotn You may also be interested in #6 issue that is the continuation of this issue.
