### ISSUE TITLE
Report average, min and max execution time in maven-memory-allocation-{date-time}.csv file.

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/maven-test-bench#6]
When `MvnValidateAllocationByMaven3VersionTest` is executed, results are exported into a `maven-memory-allocation-{date-time}.csv` file. 

For each Maven version and each measure of allocation, the execution time is reported in this CSV file thanks to #5.  In this issue we want to report the average, min and max execution time (it is already done for allocations).

The CSV generation is done in `AllocationCsvExporter` class.

**Comment by albertotn** [comment]
Well if it is possible I will work also on this
