### ISSUE TITLE
Create a daily non regression test on Maven heap allocation

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/maven-test-bench#8]
**Goal**

The aim of this issue is to develop a non regression test on Maven heap allocation with a daily execution.

**Possible implementation**

The CI build could execute the following steps:
1) Clone Maven head (build script ?)

2) Build Maven (build script ?)
```mvn -DdistributionTargetDir="{location}/apache-maven-head" clean package```

3) Clone Apache Camel (build script ?)
```
git clone -n https://github.com/apache/camel.git
git checkout c409ab7aabb971065fc8384a861904d2a2819be5
```
4) Execute a test method performing `mvn validate`  (see `MvnValidateAllocationByMaven3VersionTest`) and annotated with @MaxHeapAllocation. The threshold value should be today around 3.2 Gb.

**Comment by pcavezzan** [comment]
Hey @jeanbisutti , 
I can help you out on this 😄 

We keep in touch

**Comment by jeanbisutti** [comment]
Great @pcavezzan! :)
